2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Configure stats pid to 39400
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Loading settings from /Users/artemon/.config/wandb/settings
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Loading settings from /Users/artemon/Library/Mobile Documents/com~apple~CloudDocs/Programming/python_projects/RNN/wandb/settings
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_init.py:_log_setup():521] Logging user logs to /Users/artemon/Library/Mobile Documents/com~apple~CloudDocs/Programming/python_projects/RNN/wandb/run-20240407_001813-gkgefhht/logs/debug.log
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/artemon/Library/Mobile Documents/com~apple~CloudDocs/Programming/python_projects/RNN/wandb/run-20240407_001813-gkgefhht/logs/debug-internal.log
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x34bc71550>
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_init.py:init():561] calling init triggers
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-07 00:18:13,847 INFO    MainThread:39400 [wandb_init.py:init():611] starting backend
2024-04-07 00:18:13,848 INFO    MainThread:39400 [wandb_init.py:init():615] setting up manager
2024-04-07 00:18:13,848 INFO    MainThread:39400 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-07 00:18:13,848 INFO    MainThread:39400 [wandb_init.py:init():623] backend started and connected
2024-04-07 00:18:13,849 INFO    MainThread:39400 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-07 00:18:13,849 INFO    MainThread:39400 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-07 00:18:13,850 INFO    MainThread:39400 [wandb_init.py:init():715] updated telemetry
2024-04-07 00:18:13,850 INFO    MainThread:39400 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-07 00:18:14,321 INFO    MainThread:39400 [wandb_run.py:_on_init():2357] communicating current version
2024-04-07 00:18:14,514 INFO    MainThread:39400 [wandb_run.py:_on_init():2366] got version response 
2024-04-07 00:18:14,514 INFO    MainThread:39400 [wandb_init.py:init():799] starting run threads in backend
2024-04-07 00:18:14,568 INFO    MainThread:39400 [wandb_run.py:_console_start():2335] atexit reg
2024-04-07 00:18:14,568 INFO    MainThread:39400 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-07 00:18:14,568 INFO    MainThread:39400 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-07 00:18:14,568 INFO    MainThread:39400 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-07 00:18:14,569 INFO    MainThread:39400 [wandb_init.py:init():842] run started, returning control to user process
2024-04-07 00:18:23,764 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:18:23,764 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:19,244 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:19,250 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:19,251 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:21,370 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:21,372 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:21,372 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:25,356 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:25,358 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:25,359 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:27,529 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:27,536 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:27,537 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:30,102 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:30,103 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:30,103 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:31,278 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:32,177 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:32,178 INFO    MainThread:39400 [wandb_init.py:_pause_backend():432] pausing backend
2024-04-07 00:20:35,083 INFO    MainThread:39400 [wandb_init.py:_resume_backend():437] resuming backend
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Configure stats pid to 39400
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Loading settings from /Users/artemon/.config/wandb/settings
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Loading settings from /Users/artemon/Library/Mobile Documents/com~apple~CloudDocs/Programming/python_projects/RNN/wandb/settings
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_init.py:_log_setup():521] Logging user logs to /Users/artemon/Library/Mobile Documents/com~apple~CloudDocs/Programming/python_projects/RNN/wandb/run-20240407_002035-obn8kvre/logs/debug.log
2024-04-07 00:20:35,123 INFO    MainThread:39400 [wandb_init.py:_log_setup():522] Logging internal logs to /Users/artemon/Library/Mobile Documents/com~apple~CloudDocs/Programming/python_projects/RNN/wandb/run-20240407_002035-obn8kvre/logs/debug-internal.log
2024-04-07 00:20:35,124 INFO    MainThread:39400 [wandb_init.py:init():561] calling init triggers
2024-04-07 00:20:35,124 INFO    MainThread:39400 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {}
2024-04-07 00:20:35,124 INFO    MainThread:39400 [wandb_init.py:init():586] re-initializing run, found existing run on stack: gkgefhht
2024-04-07 00:20:35,130 INFO    MainThread:39400 [wandb_run.py:_finish():2064] finishing run artem-tm/PRAC_RNN/gkgefhht
2024-04-07 00:20:35,131 ERROR   MainThread:39400 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-04-07 00:20:35,131 INFO    MainThread:39400 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-07 00:20:35,131 INFO    MainThread:39400 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-07 00:20:35,132 INFO    MainThread:39400 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-07 00:20:35,133 INFO    MainThread:39400 [wandb_run.py:_restore():2287] restore
2024-04-07 00:20:35,133 INFO    MainThread:39400 [wandb_run.py:_restore():2293] restore done
2024-04-07 00:20:39,330 INFO    MainThread:39400 [wandb_run.py:_footer_history_summary_info():3936] rendering history
2024-04-07 00:20:39,330 INFO    MainThread:39400 [wandb_run.py:_footer_history_summary_info():3968] rendering summary
2024-04-07 00:20:39,343 INFO    MainThread:39400 [wandb_run.py:_footer_sync_info():3895] logging synced files
